# Generated by Django 4.1.5 on 2025-04-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('purchased', 'Purchsed')], default='approved', max_length=10),
            preserve_default=False,
        ),
    ]
