# Generated by Django 4.1.5 on 2025-04-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tenantuser',
            managers=[
            ],
        ),
    ]
